export const LOADING_CREATE_USER = 'LOADING_CREATE_USER';
export const SUCCESS_CREATE_USER = 'SUCCESS_CREATE_USER';
export const ERROR_CREATE_USER = 'ERROR_USER';

export const LOADING_LOGIN_USER = 'LOADING_LOGIN_USER';
export const SUCCESS_LOGIN_USER = 'SUCCESS_LOGIN_USER';
export const ERROR_LOGIN_USER = 'ERROR_LOGIN_USER';

export const LOADING_LOGOUT_USER = 'LOADING_LOGOUT_USER';
export const SUCCESS_LOGOUT_USER = 'SUCCESS_LOGOUT_USER';
export const ERROR_LOGOUT_USER = 'ERROR_LOGOUT_USER';

export const LOADING_PROFILE = 'LOADING_PROFILE';
export const SUCCESS_PROFILE = 'SUCCESS_PROFILE';
export const ERROR_PROFILE = 'ERROR_PROFILE';
